export const PRIVACY = {
  data: `
  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
‍
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for using, browsing, filling the details in the Contact us form made available on www.collegerivals.com/ 

Ampverse DMI Pvt. Ltd. and its affiliates respect your privacy. This Privacy Policy describes in brief the manner in which your data is collected and used by Ampverse DMI Pvt. Ltd. while filling the contact us form made available on www.collegerivals.com/. You are advised to please read the Privacy Policy carefully. 

By accessing, browsing www.collegerivals.com/ , you agree to the collection and use of your data by Ampverse DMI Pvt. Ltd.
The term “We” shall mean and include Ampverse DMI Pvt. Ltd.
The term “You” shall mean and include any Natural Person filling the details in the contact us form made available on www.collegerivals.com/, any natural person accessing, browsing www.collegerivals.com/

‍Rule 3(b)- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021	
‍Ampverse DMI Pvt. Ltd. herein informs you that in case of any non-compliance to this Privacy Policy, we shall the right to terminate the access or usage rights to www.collegerivals.com/
‍
‍Rule 3 (f)- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021
‍Ampverse DMI Pvt. Ltd. shall inform you regarding any changes in this Privacy Policy periodically or once a year as the case may be.

‍WHAT INFORMATION IS, OR MAY BE, COLLECTED FROM YOU?
We will automatically receive and collect certain anonymous information in standard usage logs through our Web server, including:
- web server cookie stored on your hard drive 
- an IP address, assigned to the computer which you use
- the domain server through which you access our service
- the type of computer you're using
- the type of web browser you're using
- the device id’s and other details

‍We may collect the following Personal Information about you, while filling the details in the details:
- IP Address
‍We may collect the following Sensitive Personal Data or Information (SPDI), Personal Information about you, while you fill the details specified in the Contact us form made available in www.collegerivals.com/
-Name
-Phone No
-Email id
-City
-State
-Country
-Text box – in case, there is any Sensitive Personal Data or Information (SPDI), Personal Information

‍WHO COLLECTS THE INFORMATION?
‍
‍Your Sensitive Personal Data or Information (SPDI), Personal Information may be collected, received, possessed, stored, dealt with or handled by:
Ampverse DMI Pvt. Ltd.
61-63, Second Floor, Panchkuiya Road, Connaught Place, New Delhi - 110001
‍
We will collect anonymous traffic information from you when you access and while you fill the details in the Contact us form made available on www.collegerivals.com/. 
We may collect your Sensitive Personal Data or Information (SPDI), Personal Information about you only as a part of a voluntary Contact us form made available on www.collegerivals.com/‍

‍HOW IS THE INFORMATION USED?
We use your Sensitive Personal Data or Information (SPDI), Personal Information to:
-To help us provide personalized features
-To get in touch with you 
-To preserve the history as governed by existing law or policy 


‍We use contact information internally to:
‍Direct our efforts for improvement

‍Generally, we use anonymous traffic information to:
-To provide you a better and more personalized service
-Help diagnose problems with our server
-Administer www.collegerivals.com/
-To understand how people use www.collegerivals.com/

‍PURPOSE OF COLLECTION 
‍We may collect your Sensitive Personal Data or Information (SPDI), Personal Data for the following purpose
-To connect with you to address your specific query submitted through the Contact us form made available through www.collegerivals.com/
-To provide the required details regarding your specific query 

‍DISCLOSURE POLICY IN COMPLIANCE WITH RULE 6 OF THE IT RULES 2011
‍We may share your sensitive personal data or information, personal information with third-parties for the purpose as specified in this policy.
The sensitive personal data or information may be disclosed to any person, if such disclosure is required for a lawful purpose connected with a function or activity of www.collegerivals.com/
‍The sensitive personal data or information may be disclosed, where the disclosure is necessary for compliance of a legal obligation. 
We do not rent, sell, publish or share your sensitive personal data and we will not disclose any of your personally identifiable information unless:
-We have your permission 
- to help investigate, prevent or take action regarding unlawful and illegal activities, suspected fraud, including cyber incidents potential threat, punishment of offences and to the safety or security of any person, violations of www.collegerivals.com/ ‘s terms of use or to defend against legal claims; 
- Special circumstances such as compliance with subpoenas, court orders, requests/order from legal authorities or law enforcement agencies requiring such disclosure.

‍WHAT CHOICES ARE AVAILABLE TO YOU REGARDING COLLECTION, USE AND DISTRIBUTION OF YOUR INFORMATION?
‍Sharing your sensitive personal identifiable information is entirely voluntary. However, you may be required to provide your Sensitive Personal Data or Information, Personal Information while filling the Contact us form available through www.collegerivals.com/ 

‍WHAT SECURITY PROCEDURES ARE IN PLACE TO PROTECT INFORMATION FROM LOSS, MISUSE OR ALTERATION?
To protect against the loss, misuse and alteration of the information under our control, and to comply with Rule 8 of IT Rules, 2011 (Reasonable security practices and procedures and sensitive personal data or information), we have in place appropriate physical, electronic, technical, operational and managerial procedures. Our servers are accessible only to authorized personnel and your information is shared with respective personnel to provide the services requested by you.Although we will endeavour to safeguard the confidentiality of your sensitive personal identifiable information, transmissions made by means of the Internet cannot be made absolutely secure. By filling the contact us form made available www.collegerivals.com/ in whatsoever manner, you agree that we shall have no liability for disclosure of your information due to errors in transmission or unauthorized acts of third parties including any cyber-attacks.

‍HOW CAN YOU CORRECT INACCURACIES IN THE INFORMATION?
‍To correct or update any information you have provided while filling the details specified in the Contact us form made available on www.collegerivals.com/ , you can update or correct the inaccuracies by intimating us. However, you shall be responsible for informing us the same.

‍POLICY UPDATES
‍We reserve the right to change or update this policy at any time by placing a prominent notice on www.collegerivals.com/ and shall seek your consent with respect to such updated or revised policies
  `,
};


export const TERMS = {
  data: `
 This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of www.collegerivals.com 
Your use of www.collegerivals.com is governed by the following terms and conditions (“Terms of Use”) as applicable including the applicable policies which are incorporated herein by way of reference. 
By browsing, accessing www.collegerivals.com as also while filling the details in the Contact us form made available on www.collegerivals.com , You shall be contracting with Ampverse DMI Pvt. Ltd., these terms and conditions including the policies constitute your binding obligations, with Ampverse DMI Pvt. Ltd..
For this purpose, “You” shall mean any natural person while filling the details in the Contact us form made available 
on www.collegerivals.com 
For this purpose, “Third-Party or Third-Parties” shall mean any party other than Ampverse DMI Pvt. Ltd.
For this purpose, the term “we”, “us”, “our” shall mean the Ampverse DMI Pvt. Ltd.
You shall be subject to the rules, guidelines, policies, terms, and conditions applicable to www.collegerivals.com while filling the details in the Contact us form made available through www.collegerivals.com
ONLINE INFORMATION PORTAL
Ampverse DMI Pvt. Ltd. is an intermediary and provides an information portal through www.collegerivals.com to showcase its products 
TERMS OF USE
You agree, undertake and confirm that your use of www.collegerivals.com shall be strictly governed by the following binding principles: You hereby undertake and agree not to use www.collegerivals.com for
(a) harassing or advocating harassment of another person;
(b) transmission of "junk mail”, "chain letters”, or unsolicited mass mailing or "spamming"
(c) promoting illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;
(d) transmitting, sharing, uploading links of any software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
Policy for Non- Hosting, Non- Storage, Non- Publication of Unlawful Information- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021- Part II- Rule 3 (1) (b) – Due Diligence by Intermediary
Ampverse DMI Pvt. Ltd. as an Intermediary herein informs You that it shall not host, display, upload, modify, publish, transmit, store, update or share any information that
belongs to another person and to which the user does not have any right;
is defamatory, obscene, pornographic, paedophilic, invasive of another’s privacy, including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force including bodily privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable, relating or encouraging money laundering or gambling, or otherwise inconsistent with or contrary to the laws in force;
is harmful to child;
infringes any patent, trademark, copyright or other proprietary rights;
violates any law for the time being in force;
deceives or misleads the addressee about the origin of the message or knowingly and intentionally communicates any information which is patently false or misleading in nature but may reasonably be perceived as a fact;
impersonates another person;
threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign States, or public order, or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting other nation;
contains software virus or any other computer code, file or program designed to interrupt, destroy or limit the functionality of any computer resource;
is patently false and untrue, and is written or published in any form, with the intent to mislead or harass a person, entity or agency for financial gain or to cause any injury to any person
Policy for Non- Deployment of Technical Configuration of Computer Resource- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021 – Due Diligence by Intermediary
Rule 3(k)- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021
Ampverse DMI Pvt. Ltd. as an intermediary shall not knowingly deploy or install or modify technical configuration of its computer resource – www.collegerivals.com or become party to act that may change or has the potential to change the normal course of operation of its computer resource - www.collegerivals.com than what it is supposed to perform thereby circumventing any law for the time being in force. 
Further, Ampverse DMI Pvt. Ltd. may develop, produce, distribute or employ technological means for the purpose of performing the acts of securing its computer resource – www.collegerivals.com and information contained therein;
Policy for Voluntary Removal of Information or Disabling of Access- Rule 3 (d)- (Information Technology (Intermediary Guidelines and Digital Media Ethics Code) 2021– Due Diligence by Intermediary
Ampverse DMI Pvt. Ltd. shall remove or disable access to any information, data, communication link as specified in Policy for Non- Hosting, Non- Storage, Non- Publication of Unlawful Information- Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021- Part II- Rule 3 (1) (b) – Due Diligence by Intermediary on voluntary basis or on the basis of any grievances received thereof
‍Policy for Reporting Cyber Security Incidents- Rule 3 (l) (Information Technology (Intermediary Guidelines and Digital Media Ethics Code) 2021– Due Diligence by Intermediary
Ampverse DMI Pvt. Ltd. shall report Cyber Security Incidents and share related information with the Indian Computer Response Team in accordance with the Policies and Procedures as mentioned in Information Technology (The Indian Computer Emergency Response Team and Manner of Performing Functions and Duties) Rules, 2013.
Policy for Assistance to Government Agencies- Rule 3 (j) (Information Technology (Intermediary Guidelines and Digital Media Ethics Code) 2021– Due Diligence by Intermediary
Ampverse DMI Pvt. Ltd. shall as soon as possible but not later than seventy-two hours of the receipt of an order, provide information under its control or possession, or assistance to the Government Agency which is lawfully authorised for investigative or protective or cyber securities activities, for the purposes of verification of identity, or for the prevention, detection, investigation, or prosecution, of offences under any law for the time being in force, or for cyber security incidents, however, such order shall be in writing clearly stating the purpose of seeking information or assistance, as the case may be.
PROHIBITED USE
1. You shall not use any “deep-link”, “page-scrape”, “robot”, “spider” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of www.collegerivals.com or any Content, or in any way reproduce or circumvent the navigational structure or presentation of www.collegerivals.com or  any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through www.collegerivals.com . We reserve our right to bar any such activity.
2. You shall not attempt to gain unauthorized access to any portion or feature of www.collegerivals.com or any other systems or networks connected to www.collegerivals.com or to any server, computer, network, or through www.collegerivals.com  by hacking, password “mining” or any other illegitimate means.
3. You shall not probe, scan or test the vulnerability of www.collegerivals.com or any network connected to www.collegerivals.com nor breach the security or authentication measures on www.collegerivals.com or any network connected to www.collegerivals.com . You may not reverse look-up, trace or seek to trace any information on any user of or visitor of www.collegerivals.com or exploit www.collegerivals.com or any information made available or offered by or through www.collegerivals.com in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by www.collegerivals.com 
4. You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about us or the brand name, domain name used by us including the terms www.collegerivals.com , Ampverse DMI Pvt. Ltd. or otherwise engage in any conduct or action that might tarnish the image or reputation of www.collegerivals.com , Ampverse DMI Pvt. Ltd. or otherwise tarnish or dilute any trade or service marks, trade name and/or goodwill associated with www.collegerivals.com , Ampverse DMI Pvt. Ltd.. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of www.collegerivals.com ’s systems or networks, or any systems or networks connected to www.collegerivals.com 
5. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of www.collegerivals.com 
6. You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal, You send to us on or through www.collegerivals.com . You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.
7. You may not use www.collegerivals.com  or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Ampverse DMI Pvt. Ltd. and/ others
8. You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules there under as applicable and as amended from time to time and also all applicable laws, rules and regulations.
9. You may not transmit any chain letters or unsolicited commercial or junk email via www.collegerivals.com 
10. It shall be a violation of these Terms of Use to use any information obtained from www.collegerivals.com or use www.collegerivals.com in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than us without our prior explicit consent. In order to protect our users from such advertising or solicitation, we reserve the right to restrict your usage of www.collegerivals.com for a reasonable period which we deem appropriate in our sole discretion. 
11. You understand that we have the right at all times to disclose any information (including the identity of the persons providing information through the Contact us form made available on www.collegerivals.com including any information uploaded through any of the services made available through www.collegerivals.com  as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, we can (and You hereby expressly authorize us to) disclose any information about You to law enforcement or other government officials, as we, in our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.
12. We reserve the right, but has no obligation, to monitor the materials posted on www.collegerivals.com , Ampverse DMI Pvt. Ltd. shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. In no event shall Ampverse DMI Pvt. Ltd. assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on www.collegerivals.com 
13. It is possible that any users or third-parties (including unauthorized users or “hackers”) may post or transmit offensive or obscene materials on www.collegerivals.com  and that You may be involuntarily exposed to such offensive and obscene materials. We do not approve of such unauthorized use.
14.  www.collegerivals.com shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).
15.  You shall not reverse engineer www.collegerivals.com  in whatsoever manner
CONTENTS POSTED 
The graphics, interfaces, visual interfaces, technology, software with respect to www.collegerivals.com  shall be solely owned by Ampverse DMI Pvt. Ltd.
Further, the trademarks relating to the brand name, logo of BUSINESS NAME displayed on www.collegerivals.com  shall be the sole property of Ampverse DMI Pvt. Ltd.
However,  www.collegerivals.com  may also contain description, images, content which is considered as third-party content. 
Ampverse DMI Pvt. Ltd. hereby acknowledges that such third-party content is owned by the respective owners.
COMMENTS- TERMS & CONDITIONS
You herein agree to the following terms and conditions while making use of Comments Option made available through the Contact us form made available on www.collegerivals.com 
You shall in no event violate any policies and these guidelines while using www.collegerivals.com 
You shall in no event make post, share any content, information that is harmful, threatening, abusive, harassing, tortious, indecent, defamatory, discriminatory, vulgar, profane, obscene, libelous, hateful or otherwise objectionable
You shall in no event violate any right, including, but not limited to, right of privacy, right of publicity, copyright, trademark, patent, trade secret, or any other intellectual property or proprietary rights
You shall in no event disguise attempting to disguise the origin of the content, information or share such content, information under a fake or false name. However, the same also constitute a knowingly erroneous or unethical content, information
You shall in no event share, transmit, upload any information, content that causes or is likely to cause any conflict of interest
You shall in no event promote, solicit, like, share any information that is obscene, pornographic, pedophilic in nature
You shall in no event harass, stalk, mislead, misrepresent any individual, entity while filling the Comments option provided made available through Contact us form made available on www.collegerivals.com
You shall be required to maintain decency and decorum while filling the Comments option provided made available through the Contact us form made available on www.collegerivals.com 
You shall in no event promote, share, solicit any activity, image, video, link that is affecting the reputation, goodwill, brand name of any entity, individual
You shall in no event promote, share, transmit, solicit any information, image, video, link that is illegal, prohibited by law in whatsoever manner
You shall in no event solicit, infringe the privacy of any individual in whatsoever manner
You shall in no event violate, infringe, breach the Intellectual Property of any entity, individual
You shall in no event share Sensitive Personal Data or Information, Personal Information 
You shall in no event exaggerate, falsely represent, misrepresent any information or content including the language and emoji’s
You shall in no event make use of any emoji’s causing any defamatory, derogatory, harassing, stalking, discriminating, hateful, harming the reputation, privacy of any individual, entity or otherwise objectionable
In no event shall Ampverse DMI Pvt. Ltd. hold any responsibility, liability for any of the above in whatsoever manner
GENERAL OBLIGATIONS
You shall be obliged to provide accurate information while filling up the Contact us form made available through www.collegerivals.com
You shall also adhere to the minimum age requirement i.e., 18 years as defined by the law of the land 
You shall read all the policies, terms mentioned in www.collegerivals.com
You shall not copy or use the information contained in www.collegerivals.com
You shall not engage in any activities mentioned in “PROHIBITED USE” (mentioned herein) either directly, indirectly or in whatsoever manner 
PRIVACY
We view protection of Your privacy as a very important principle. We understand clearly that You and Your Sensitive Personal Information is one of our most important assets. We store and process Your Sensitive Personal Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under. Our Privacy Policy is available for more details.
THIRD-PARTYAPI’s/ LINKS
www.collegerivals.com may also be integrated with third-party API’s. However, in no event shall Ampverse DMI Pvt. Ltd. hold any responsibility, liability in this regard.
LEGAL DISCLAIMER

www.collegerivals.com and all content, included on or otherwise made available to You thereof are provided on “as is” and “as available” basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, we, Ampverse DMI Pvt. Ltd. do not warrant that: -
www.collegerivals.com shall be constantly available, or available at all; or the information on www.collegerivals.com, is complete, true, accurate or non-misleading.
We, Ampverse DMI Pvt. Ltd. do not warrant that www.collegerivals.com , information, Content, Images, Descriptions on or otherwise made available to You thereof, their servers; or electronic communication sent from us are free of viruses or other harmful components.
Nothing on www.collegerivals.com is meant to constitute advice of any kind.
Ampverse DMI Pvt. Ltd., we disclaim any damages, liabilities, loss, claims including ANY SPECIAL, INCIDENTAL, INDIRECT or CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION OR ARISING OUT OF YOUR USE OF www.collegerivals.com 
OUR LIABILITY 
We shall be liable for any technical and relative issue with regard to www.collegerivals.com . However, we shall hold no liability for unforeseen circumstances, force majeure events and situations beyond our control
THIRD PARTY LIABILITY 
The Third-Party shall be solely and exclusively liable for any and all issues arising out of third-party API’s, plugins, integrations connected to www.collegerivals.com .  In no event shall Ampverse DMI Pvt. Ltd. hold any liability for third-party issues or failure
YOUR LIABILITY
You shall be liable for all and all information provided by you upon while filling the details in Contact us form made available through www.collegerivals.com 
FORCE MAJEURE
In no event shall Ampverse DMI Pvt. Ltd. be responsible for any failure to perform any services due to causes beyond its control, including but not limited to acts of God, war, and riot, acts of or military authorities, fire, floods or accident(s), pandemic & emergency situations etc.
INDEMNITY
You shall indemnify and hold harmless Ampverse DMI Pvt. Ltd., its directors, agents, and employees, from any claim or demand, or actions made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
APPLICABLE LAW / JURISDICTION 
Terms of Use shall be governed by and interpreted and construed in accordance with the laws of India. The place of jurisdiction shall be Delhi India
DESCRIPTION
Ampverse DMI Pvt. Ltd. does not warrant that description or other content made available on www.collegerivals.com is accurate, complete, reliable, current, or error-free and assumes no liability in this regard 
LIMITATION OF LIABILITY
IN NO EVENT SHALL Ampverse DMI Pvt. Ltd. BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE
www.collegerivals.com may include inaccuracies and typographical errors. Changes and improvements are periodically made to www.collegerivals.com 
  `,
};
