export const ContactCities = ["Delhi","Pune","Mumbai","Hyderabad","Bangalore"]
export const RegistrationCities = [
  'Mumbai',
  'Pune',
  'Jaipur',
  'Indore',
  'Bhopal',
  'Ahmedabad',
  'Jalandhar',
  'Chandigarh',
  'Dehradun',
  'Delhi',
  'Lucknow',
  'Patna',
  'Gauhati',
  'Kolkata',
  'Bhubaneshwar',
  'Vizag',
  'Hyderabad',
  'Bangalore',
  'Chennai',
  'Kochi',
  'Mangaluru',
  'Goa',
  'Other'
];